name: word_wise
packages:
  - .

scripts:
  get: fvm flutter pub get

  fix-gen: "mkdir -p .dart_tool/flutter_gen/ && echo 'name: stub'> .dart_tool/flutter_gen/pubspec.yaml"

  l10n: "flutter gen-l10n && arb_utils sort lib/l10n/app_en.arb"

  gen: "dart run build_runner build --delete-conflicting-outputs || make try-fix-gen"
